"""Add is_redeemed and redeemed_timestamp to Redemption model

Revision ID: ab1e9491f1ee
Revises: d9f82f843d33
Create Date: 2024-09-26 17:21:01.389675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1e9491f1ee'
down_revision = 'd9f82f843d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_redeemed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('redeemed_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemption', schema=None) as batch_op:
        batch_op.drop_column('redeemed_timestamp')
        batch_op.drop_column('is_redeemed')

    # ### end Alembic commands ###
